class DistrictRecycling {
  final String district;
  final bool glass;
  final bool metal;
  final bool paperCardboard;
  final bool plasticPETE;
  final bool plasticPVC;
  final bool plasticHDPE;
  final bool plasticPP;
  final bool smallElectrics;
  final bool gardenWaste;

  const DistrictRecycling({
    required this.district,
    required this.glass,
    required this.metal,
    required this.paperCardboard,
    required this.plasticPETE,
    required this.plasticPVC,
    required this.plasticHDPE,
    required this.plasticPP,
    required this.smallElectrics,
    required this.gardenWaste,
  });
}

const List<DistrictRecycling> recyclingData = [
  DistrictRecycling(
    district: 'Erean',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: true,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Brunad',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: true,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Bylyn',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Docia',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Marend',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Pryn',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Zord',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Yaean',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Frestin',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Stonyam',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Ryall',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
  DistrictRecycling(
    district: 'Ruril',
    glass: true,
    metal: true,
    paperCardboard: true,
    plasticPETE: true,
    plasticPVC: false,
    plasticHDPE: true,
    plasticPP: true,
    smallElectrics: false,
    gardenWaste: true,
  ),
];
